#!/usr/bin/sh

PAGE=$(cat ~/.config/qutebrowser/quickmarks | awk '{print substr($1, 0)}' | dmenu -p 'Site: ')
if [ "$PAGE" != "" ] 
then 
	SITE="$(grep $PAGE ~/.config/qutebrowser/quickmarks | awk '{print substr($2, 0)}')"
	if [ "$SITE" == "" ]
	then
		qutebrowser $PAGE
	else
		qutebrowser $SITE
	fi
fi
