#!/usr/bin/sh
# author GG weebcyberpunk@gmail.com
# version 0.0.0
# since Mar 19, 2022

ACTIONS=("logout\nrestart\nshutdown\nlock\nsuspend")
CHOICE="$(echo -e $ACTIONS | dmenu -p 'Action: ')"

if [ "$CHOICE" == "logout" ]
then
	killall dwm

elif [ "$CHOICE" == "restart" ]
then
	systemctl restart

elif [ "$CHOICE" == "shutdown" ]
then
	systemctl poweroff

elif [ "$CHOICE" == "lock" ]
then
	slock &
	while :
	do
		if [ "$(pstree | grep slock)" != "" ]
		then
			sleep 5s

		else
			exit

		fi
	done

elif [ "$CHOICE" == "suspend" ]
then
	$HOME/.local/share/bin/suspend.sh

fi
